name: steamcommunity
description: A Dart package that providing access to the Steam Community.
version: 0.0.2
publish_to: none
repository: https://github.com/VadimMalykhin/steamcommunity.dart

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  equatable: ^2.1.0
  html: ^0.15.6
  xml: ^6.6.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.2
